### ISSUE TITLE
Document SDK

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansible-sdk#14]
We need files created in the docs folder of the SDK for the following - 

- Add the SDK to your project
- Getting started
- API documentation
- Examples
- FAQs
- Usage Scenarios / how to’s
- Debugging/troubleshooting

**Comment by eqrx** [comment]
Hey, where are the getting started and faq parts located?

**Comment by Akasurde** [comment]
FAQs and Getting Started were already covered in the document, so keeping it was superfluous.
